# bot/handlers/performance.py

import logging
from telegram import Update
from telegram.ext import ContextTypes
from bot.analytics.performance_tracker import get_performance_summary
from bot.analytics.win_loss_report import generate_win_loss_report
from bot.utils.error_reporter import report_error

# Setup logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

async def performance(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Handler for /performance command.
    Shows real-time trading performance metrics.
    """
    chat_id = update.effective_chat.id
    user = update.effective_user.first_name or "Trader"

    try:
        summary = get_performance_summary()
        await context.bot.send_message(chat_id=chat_id, text=summary, parse_mode="Markdown")
        logger.info(f"Performance report requested by {user}")

    except Exception as e:
        await report_error(context.bot, chat_id, e, context_info="Performance Command Error")
        logger.error(f"Performance command error: {e}")

async def winloss(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Handler for /winloss command.
    Generates a full win/loss trading report.
    """
    chat_id = update.effective_chat.id
    user = update.effective_user.first_name or "Trader"

    try:
        report = generate_win_loss_report()
        await context.bot.send_message(chat_id=chat_id, text=report, parse_mode="Markdown")
        logger.info(f"Win/Loss report generated by {user}")

    except Exception as e:
        await report_error(context.bot, chat_id, e, context_info="WinLoss Command Error")
        logger.error(f"WinLoss command error: {e}")
